services:
  app:
    image: tianon/true
    volumes:
      - .:/rails

  rails_app_teste:
    container_name: teste-dev
    build: .
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
    command: bash -c "bundle install && bin/rails server -p 3000 -b '0.0.0.0'"
    volumes_from:
      - app
    ports:
      - "3000:3000"
    mem_limit: 2048m
